# Generated by Django 3.0 on 2022-05-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
